### PR TITLE
Docs: perturbation explanation

### PR DESCRIPTION
**Pull request by oliviamb**
Starting an explanation on our approach to data perturbations. I still intend to add more to this today, but feel free to take a look and let me know your thoughts on how it's going so far. Especially what should/shouldn't be included in this

### CODE REVIEW

**Review by jgbos — APPROVED** [review]

**Comment by rsokl** [comment]
Reviewing right now

**Comment by rsokl** [comment]
@oliviamb  and @jgbos  I made substantial edits to this section:

- Renamed to "On Data Perturbations" (i.e. this is "Explanation on Data Perturbations"
- Added a opening sentence "This article ..."
- Added annotations to the notional `perturbation_solver`
- Called out the explicit roles of the pert model vs optimizer
- Updated the pseudo-code for the pert-model and pert-optimizer
- Showed that we can solve for perturbations using a completely standard PyTorch trainer

**Comment by jgbos** [comment]
@rsokl great, I was fine with content and wondered how much we wanted pseudo-code to represent what's in our code in an explanation.  I'll look it over.

**Comment by jgbos** [comment]
It might be good to add a line after `standard_trainer` demonstrating getting a perturbation, e.g.,

```python
# perturb a given data point given the optimized perturbation model
pert_data = pert_model(data)
```

**Pull request merged**
